-- Styles --
INSERT INTO styles (name) VALUES ('American Amber Ale');
INSERT INTO styles (name) VALUES ('American Amber Lager');
INSERT INTO styles (name) VALUES ('American Barley Wine');
INSERT INTO styles (name) VALUES ('American Black Ale');
INSERT INTO styles (name) VALUES ('American Brett');
INSERT INTO styles (name) VALUES ('American Brown Ale');
INSERT INTO styles (name) VALUES ('American Cream Ale');
INSERT INTO styles (name) VALUES ('American Imperial Porter');
INSERT INTO styles (name) VALUES ('American Imperial Red Ale');
INSERT INTO styles (name) VALUES ('American Imperial Stout');
INSERT INTO styles (name) VALUES ('American India Pale Ale/IPA');
INSERT INTO styles (name) VALUES ('American Lager');
INSERT INTO styles (name) VALUES ('American Pale Ale');
INSERT INTO styles (name) VALUES ('American Sour');
INSERT INTO styles (name) VALUES ('American Stout');
INSERT INTO styles (name) VALUES ('American-Style Wheat Wine Ale');
INSERT INTO styles (name) VALUES ('American Wheat');
INSERT INTO styles (name) VALUES ('Baltic-Style Porter');
INSERT INTO styles (name) VALUES ('Barrel-Aged Beer');
INSERT INTO styles (name) VALUES ('Belgian-Style Blonde Ale');
INSERT INTO styles (name) VALUES ('Belgian-Style Dubbel');
INSERT INTO styles (name) VALUES ('Belgian-Style Flanders');
INSERT INTO styles (name) VALUES ('Belgian-Style Fruit Lambic');
INSERT INTO styles (name) VALUES ('Belgian-Style Golden Strong Ale');
INSERT INTO styles (name) VALUES ('Belgian-Style Lambic/Gueuze');
INSERT INTO styles (name) VALUES ('Belgian-Style Pale Ale');
INSERT INTO styles (name) VALUES ('Belgian-Style Quadrupel');
INSERT INTO styles (name) VALUES ('Belgian-Style Saison');
INSERT INTO styles (name) VALUES ('Belgian-Style Tripel');
INSERT INTO styles (name) VALUES ('Belgian-Style Witbier');
INSERT INTO styles (name) VALUES ('Berliner-Style Weisse');
INSERT INTO styles (name) VALUES ('French-Style Biere de Garde');
INSERT INTO styles (name) VALUES ('English-Style Bitter');
INSERT INTO styles (name) VALUES ('Blonde Ale');
INSERT INTO styles (name) VALUES ('Bohemian-Style Pilsener');
INSERT INTO styles (name) VALUES ('British-Style Barley Wine Ale');
INSERT INTO styles (name) VALUES ('California Common');
INSERT INTO styles (name) VALUES ('Chocolate Beer');
INSERT INTO styles (name) VALUES ('Coffee Beer');
INSERT INTO styles (name) VALUES ('Contemporary Gose');
INSERT INTO styles (name) VALUES ('English-Style Brown Ale');
INSERT INTO styles (name) VALUES ('English-Style Brown Porter');
INSERT INTO styles (name) VALUES ('English-Style Mild');
INSERT INTO styles (name) VALUES ('English-Style India Pale Ale/IPA');
INSERT INTO styles (name) VALUES ('English-Style Oatmeal Stout');
INSERT INTO styles (name) VALUES ('English-Style Old Ale');
INSERT INTO styles (name) VALUES ('English-Style Pale Ale/ESB');
INSERT INTO styles (name) VALUES ('English-Style Sweet Stout (Milk Stout)');
INSERT INTO styles (name) VALUES ('European-Style Export');
INSERT INTO styles (name) VALUES ('Fruit and Field Beer');
INSERT INTO styles (name) VALUES ('German-Style Bock');
INSERT INTO styles (name) VALUES ('German-Style Brown/Altbier');
INSERT INTO styles (name) VALUES ('German-Style Doppelbock');
INSERT INTO styles (name) VALUES ('German-Style Dunkel');
INSERT INTO styles (name) VALUES ('German-Style Dunkelweizen');
INSERT INTO styles (name) VALUES ('German-Style Hefeweizen');
INSERT INTO styles (name) VALUES ('German-Style Maibock');
INSERT INTO styles (name) VALUES ('German-Style Helles');
INSERT INTO styles (name) VALUES ('German-Style Kolsch');
INSERT INTO styles (name) VALUES ('German-Style Marzen / Oktoberfest');
INSERT INTO styles (name) VALUES ('German-Style Pilsener');
INSERT INTO styles (name) VALUES ('German-Style Schwarzbier');
INSERT INTO styles (name) VALUES ('German-Style Weizenbock');
INSERT INTO styles (name) VALUES ('Gluten Free');
INSERT INTO styles (name) VALUES ('Herb and Spice Beer');
INSERT INTO styles (name) VALUES ('Honey Beer');
INSERT INTO styles (name) VALUES ('Imperial India Pale Ale');
INSERT INTO styles (name) VALUES ('Irish-Style Dry Stout');
INSERT INTO styles (name) VALUES ('Irish-Style Red');
INSERT INTO styles (name) VALUES ('Pumpkin Beer');
INSERT INTO styles (name) VALUES ('Robust Porter');
INSERT INTO styles (name) VALUES ('Rye Beer');
INSERT INTO styles (name) VALUES ('Scotch Ale/Wee Heavy');
INSERT INTO styles (name) VALUES ('Scottish-Style Ale');
INSERT INTO styles (name) VALUES ('Session Beer');
INSERT INTO styles (name) VALUES ('Smoke Porter');
INSERT INTO styles (name) VALUES ('Specialty Beer');
INSERT INTO styles (name) VALUES ('Vienna-Style Lager');

-- few hops --
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Admiral',	'UK',	14.8,	'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Ahtanum', 'USA',	6.0, 'AROMATYCZNY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Amarillo Gold', 'USA',	8.5 ,'AROMATYCZNY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Aquila', 'USA',	6.5 ,'AROMATYCZNY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Banner', 'USA',	10.0, 'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Bramling Cross','UK',	6.0,'AROMATYCZNY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Brewers Gold','UK',	8.0,'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Bullion','UK',	8.0	,'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Cascade', 'USA',	5.5,'UNIWERSALNY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Centennial'	, 'USA',	10.0,'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Challenger','UK',	7.5,'AROMATYCZNY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Chinook'	, 'USA',	13.0 ,'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Cluster'	, 'USA',	7.0 ,'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Columbia',	'UK',	5.5 ,'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Columbus(Tomahawk)', 'USA',	14.0,'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Comet',	'USA',	9.5 ,	'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Eroica',	'USA',	13.0,	'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('First Gold',	'UK',	7.5 ,	'UNIWERSALNY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Fuggles',	'UK',	4.5, 'AROMATYCZNY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Galena',	'USA',	13.0, 'GORYCZKOWY');
INSERT INTO hops(name, country, alpha, hop_type) VALUES ('Glacier'	,'USA',	5.6, 'AROMATYCZNY');
-- few malts --
INSERT INTO malts(name, country, malt_type, colorebc, potential, max) VALUES ('Acid Malt', 'Germany',	'SŁÓD',	6, 27, 10.0);
INSERT INTO malts(name, country, malt_type, colorebc, potential, max) VALUES ('Amber Malt',	'United Kingdom',	'SŁÓD',	44, 35, 20.0);
INSERT INTO malts(name, country, malt_type, colorebc, potential, max) VALUES ('Aromatic Malt',	'Belgium',	'SŁÓD',	52, 36, 10.0);
-- few yeasts --
INSERT INTO yeasts(name, lab, symbol, type, packaging, attenuation) VALUES ('Nottingham', 'Danstar', '', 'ALE', 'SUCHE', 77.0);
INSERT INTO yeasts(name, lab, symbol, type, packaging, attenuation) VALUES ('Pilsner Lager',	'White Labs',	'WLP800',	'LAGER',	'PŁYNNE', 80);
INSERT INTO yeasts(name, lab, symbol, type, packaging, attenuation) VALUES ('American Lager',	'White Labs',	'WLP840',	'LAGER',	'PŁYNNE', 70);
INSERT INTO yeasts(name, lab, symbol, type, packaging, attenuation) VALUES ('English Ale',	'White Labs',	'WLP002',	'ALE',	'PŁYNNE',	90);
INSERT INTO yeasts(name, lab, symbol, type, packaging, attenuation) VALUES ('German Wheat',	'Brewtek',	'CL-0920',	'WHEAT',	'PŁYNNE',	72);
INSERT INTO yeasts(name, lab, symbol, type, packaging, attenuation) VALUES ('Saison',	'Brewtek',	'CL-0380',	'ALE',	'PŁYNNE',	73);
INSERT INTO yeasts(name, lab, symbol, type, packaging, attenuation) VALUES ('Kolsch',	'Brewtek',	'CL-0400',	'ALE',	'PŁYNNE',	76);
INSERT INTO yeasts(name, lab, symbol, type, packaging, attenuation) VALUES ('Trappist High Gravity',	'Wyeast Labs', '3787', 'WHEAT',	'PŁYNNE', 77);

-- User: test@test.tt test | pass: test123 --
INSERT INTO users(id_user, email, password, username) VALUES (1, 'test@test.tt', '$2a$10$4H9UaHRn/mDvVCTpTesbpegGuWDlW.AbjHCN/ZIxYozIILX0opmNK', 'test');
